name: "Positron: CI - Merge to main"

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      smoketest_target:
        required: false
        description: "Smoketest suite to run, e.g. smoketest-merge-to-main or smoketest-pr"
        default: "smoketest-merge-to-main"
        type: string
  workflow_dispatch:
    inputs:
      smoketest_target:
        required: false
        description: "Smoketest suite to run, e.g. smoketest-merge-to-main or smoketest-pr"
        default: "smoketest-merge-to-main"
        type: string

env:
  SMOKETEST_TARGET: ${{ inputs.smoketest_target || 'smoketest-merge-to-main' }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      POSITRON_BUILD_NUMBER: 0 # CI skips building releases

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: AWS S3 Access Setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.QA_AWS_RO_ROLE }}
          aws-region: ${{ secrets.QA_AWS_REGION }}

      # Restore cache for root node_modules
      - name: Restore cache for node_modules
        id: cache-node-modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: root-node-modules-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            root-node-modules-v2-${{ runner.os }}-

      # Restore cache for build
      - name: Restore cache for build
        id: cache-build
        uses: actions/cache/restore@v4
        with:
          path: build/node_modules
          key: build-node-modules-v3-${{ runner.os }}-${{ hashFiles('build/yarn.lock') }}
          restore-keys: |
            build-node-modules-v3-${{ runner.os }}-

      # Restore cache for extensions
      - name: Restore cache for extensions
        id: cache-extensions
        uses: actions/cache/restore@v4
        with:
          path: |
            extensions
            extensions/**/node_modules
          key: extensions-v3-${{ runner.os }}-${{ hashFiles('extensions/yarn.lock') }}
          restore-keys: |
            extensions-v3-${{ runner.os }}-

      # Restore cache for remote
      - name: Restore cache for remote
        id: cache-remote
        uses: actions/cache/restore@v4
        with:
          path: |
            remote/node_modules
            remote/**/node_modules
          key: remote-node-modules-v2-${{ runner.os }}-${{ hashFiles('remote/yarn.lock') }}
          restore-keys: |
            remote-node-modules-v2-${{ runner.os }}-

      - name: Execute yarn
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
          POSITRON_GITHUB_PAT: ${{ github.token }}
        run: |
          # Install Yarn
          npm install -g yarn

          # Install node-gyp; this is required by some packages, and yarn
          # sometimes fails to automatically install it.
          yarn global add node-gyp

          # Perform the main yarn command; this installs all Node packages and
          # dependencies
          yarn --immutable --network-timeout 120000
          yarn --cwd test/automation install --frozen-lockfile
          yarn --cwd test/smoke install --frozen-lockfile

      # Cache root node_modules if cache miss
      - name: Cache root node_modules
        if: always() && steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: root-node-modules-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      # Cache build node_modules if cache miss
      - name: Cache build node_modules
        if: always() && steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: build/node_modules
          key: build-node-modules-v3-${{ runner.os }}-${{ hashFiles('build/yarn.lock') }}

      # Cache extensions node_modules if cache miss
      - name: Cache extensions node_modules
        if: always() && steps.cache-extensions.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            extensions
            extensions/**/node_modules
          key: extensions-v3-${{ runner.os }}-${{ hashFiles('extensions/yarn.lock') }}

      # Cache remote node_modules if cache miss
      - name: Cache remote node_modules
        if: always() && steps.cache-remote.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            remote/node_modules
            remote/**/node_modules
          key: remote-node-modules-v2-${{ runner.os }}-${{ hashFiles('remote/yarn.lock') }}

      - name: Compile and Download
        run: yarn npm-run-all --max_old_space_size=4095 -lp compile "electron x64" playwright-install download-builtin-extensions

      # Upload the build artifacts to be used by downstream jobs
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/
            extensions/
            remote/

  unit-integration-tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      POSITRON_BUILD_NUMBER: 0 # CI skips building releases
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Pull Docker image
        run: docker pull mdefurio/positron-tests:latest

      - name: Run Unit Tests (node.js)
        id: nodejs-unit-tests
        if: always()
        run: |
          docker run --rm \
            -v $(pwd):/usr/src/positron \
            -w /usr/src/positron \
            mdefurio/positron-tests:latest \
            bash -c "yarn test-node"

      - name: Compile Integration Tests
        run: yarn --cwd test/integration/browser compile

      - name: Run Integration Tests (Electron)
        id: electron-integration-tests
        if: always()
        run: |
          docker run --rm \
            -e DISPLAY=:10 \
            -v $(pwd):/usr/src/positron \
            -w /usr/src/positron \
            mdefurio/positron-smoke-tests:latest \
            bash -c "service xvfb start && ps aux | grep Xvfb && yarn test-node && \
              DISPLAY=:10 ./scripts/test-integration-pr.sh"

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      POSITRON_BUILD_NUMBER: 0 # CI skips building releases
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Pull Docker image
        run: docker pull mdefurio/positron-tests:latest

      - name: Compile Smoke Tests
        run: yarn --cwd test/smoke compile

      - name: Run Smoke Tests (Electron)
        id: electron-smoke-tests
        if: always()
        #   run: DISPLAY=:10 yarn ${{ env.SMOKETEST_TARGET }} --tracing
        run: |
          docker run --rm \
            -e DISPLAY=:10 \
            -e POSITRON_PY_VER_SEL=3.10.12 \
            -e POSITRON_R_VER_SEL=4.4.0 \
            -e SMOKETEST_TARGET=${{ env.SMOKETEST_TARGET }} \
            -v $(pwd):/usr/src/positron \
            -w /usr/src/positron \
            mdefurio/positron-smoke-tests:latest \
            bash -c "service xvfb start && ps aux | grep Xvfb && \
              DISPLAY=:10 yarn $SMOKETEST_TARGET --tracing"

      # - name: Set TestRail Run Title
      #   id: set-testrail-run-title
      #   if: always()
      #   run: echo "TESTRAIL_TITLE=$(date +'%Y-%m-%d') Smoke Tests on branch $GITHUB_REF_NAME" >> $GITHUB_ENV

      # - name: Upload Test Results to TestRail
      #   id: testrail-upload
      #   if: always()
      #   run: trcli --host "https://posit.testrail.io/" --project Positron --username testrailautomation@posit.co --key ${{ secrets.TESTRAIL_API_KEY }} parse_junit --file ".build/logs/smoke-tests-electron/test-results/results.xml" --case-matcher name --title "$TESTRAIL_TITLE" --close-run

      # - name: Upload run artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: run-artifacts
      #     path: .build/logs/smoke-tests-electron/

      # - name: slack-smoke-test-report
      #   if: ${{ failure() && env.SMOKETEST_TARGET == 'smoketest-merge-to-main' }}
      #   uses: testlabauto/xunit-slack-reporter@v2.0.1
      #   env:
      #     SLACK_CHANNEL: C07FR1JNZNJ #positron-test-results channel
      #     SLACK_TOKEN: ${{ secrets.SMOKE_TESTS_SLACK_TOKEN }}
      #     XUNIT_PATH: .build/logs/smoke-tests-electron/test-results/results.xml
